common: &common
  adapter: postgresql
  username: sample_app
  password: pgsql123 # from psql setup, see Postgresql

development:
  <<: *common
  database: sample_app_development

test:
  <<: *common
  database: sample_app_test

production:
  <<: *common
  database: sample_app_production